# Generated by Django 5.2.7 on 2025-10-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='timezone',
            field=models.CharField(choices=[('America/Mexico_City', 'Mexico City (UTC-6/-5)'), ('America/Cancun', 'Cancún (UTC-5)'), ('America/Bogota', 'Bogotá (UTC-5)'), ('America/Lima', 'Lima (UTC-5)'), ('America/Santiago', 'Santiago (UTC-4/-3)'), ('America/Buenos_Aires', 'Buenos Aires (UTC-3)'), ('America/Sao_Paulo', 'São Paulo (UTC-3/-2)'), ('America/Caracas', 'Caracas (UTC-4)'), ('America/Havana', 'Havana (UTC-5/-4)'), ('America/Santo_Domingo', 'Santo Domingo (UTC-4)'), ('America/Panama', 'Panama City (UTC-5)'), ('America/Costa_Rica', 'San José (UTC-6)'), ('America/Tegucigalpa', 'Tegucigalpa (UTC-6)'), ('America/Guatemala', 'Guatemala City (UTC-6)'), ('America/Managua', 'Managua (UTC-6)'), ('America/El_Salvador', 'San Salvador (UTC-6)'), ('America/Montevideo', 'Montevideo (UTC-3)'), ('America/Asuncion', 'Asunción (UTC-4/-3)'), ('America/La_Paz', 'La Paz (UTC-4)'), ('America/Guayaquil', 'Guayaquil (UTC-5)')], default='America/Mexico_City', max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='whatsapp_phone_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
