# Generated by Django 5.2.7 on 2025-10-28 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_company_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='timezone',
            field=models.CharField(choices=[('America/Mexico_City', 'Mexico - Mexico City (UTC-6)'), ('America/Cancun', 'Mexico - Cancún (UTC-5)'), ('America/Mazatlan', 'Mexico - Mazatlán (UTC-7)'), ('America/Tijuana', 'Mexico - Tijuana (UTC-8)'), ('America/Hermosillo', 'Mexico - Hermosillo (UTC-7)'), ('America/Chihuahua', 'Mexico - Chihuahua (UTC-6)'), ('America/Monterrey', 'Mexico - Monterrey (UTC-6)'), ('America/Merida', 'Mexico - Mérida (UTC-6)'), ('America/Guatemala', 'Guatemala - Guatemala City (UTC-6)'), ('America/Belize', 'Belize - Belize City (UTC-6)'), ('America/El_Salvador', 'El Salvador - San Salvador (UTC-6)'), ('America/Tegucigalpa', 'Honduras - Tegucigalpa (UTC-6)'), ('America/Managua', 'Nicaragua - Managua (UTC-6)'), ('America/Costa_Rica', 'Costa Rica - San José (UTC-6)'), ('America/Panama', 'Panama - Panama City (UTC-5)'), ('America/Havana', 'Cuba - Havana (UTC-5)'), ('America/Port-au-Prince', 'Haiti - Port-au-Prince (UTC-5)'), ('America/Santo_Domingo', 'Dominican Republic - Santo Domingo (UTC-4)'), ('America/Jamaica', 'Jamaica - Kingston (UTC-5)'), ('America/Puerto_Rico', 'Puerto Rico - San Juan (UTC-4)'), ('America/Martinique', 'Martinique - Fort-de-France (UTC-4)'), ('America/Guadeloupe', 'Guadeloupe - Basse-Terre (UTC-4)'), ('America/Barbados', 'Barbados - Bridgetown (UTC-4)'), ('America/Port_of_Spain', 'Trinidad and Tobago - Port of Spain (UTC-4)'), ('America/Curacao', 'Curaçao - Willemstad (UTC-4)'), ('America/Aruba', 'Aruba - Oranjestad (UTC-4)'), ('America/Caracas', 'Venezuela - Caracas (UTC-4)'), ('America/Bogota', 'Colombia - Bogotá (UTC-5)'), ('America/Guayaquil', 'Ecuador - Guayaquil (UTC-5)'), ('America/Lima', 'Peru - Lima (UTC-5)'), ('America/La_Paz', 'Bolivia - La Paz (UTC-4)'), ('America/Paramaribo', 'Suriname - Paramaribo (UTC-3)'), ('America/Cayenne', 'French Guiana - Cayenne (UTC-3)'), ('America/Guyana', 'Guyana - Georgetown (UTC-4)'), ('America/Sao_Paulo', 'Brazil - São Paulo (UTC-3)'), ('America/Rio_Branco', 'Brazil - Rio Branco, Acre (UTC-5)'), ('America/Manaus', 'Brazil - Manaus, Amazonas (UTC-4)'), ('America/Fortaleza', 'Brazil - Fortaleza (UTC-3)'), ('America/Recife', 'Brazil - Recife (UTC-3)'), ('America/Belem', 'Brazil - Belém (UTC-3)'), ('America/Salvador', 'Brazil - Salvador (UTC-3)'), ('America/Campo_Grande', 'Brazil - Campo Grande (UTC-4)'), ('America/Cuiaba', 'Brazil - Cuiabá (UTC-4)'), ('America/Porto_Velho', 'Brazil - Porto Velho (UTC-4)'), ('America/Boa_Vista', 'Brazil - Boa Vista (UTC-4)'), ('America/Santarem', 'Brazil - Santarém (UTC-3)'), ('America/Araguaina', 'Brazil - Araguaína (UTC-3)'), ('America/Maceio', 'Brazil - Maceió (UTC-3)'), ('America/Noronha', 'Brazil - Fernando de Noronha (UTC-2)'), ('America/Eirunepe', 'Brazil - Eirunepé (UTC-5)'), ('America/Argentina/Buenos_Aires', 'Argentina - Buenos Aires (UTC-3)'), ('America/Argentina/Cordoba', 'Argentina - Córdoba (UTC-3)'), ('America/Argentina/Salta', 'Argentina - Salta (UTC-3)'), ('America/Argentina/Tucuman', 'Argentina - Tucumán (UTC-3)'), ('America/Argentina/La_Rioja', 'Argentina - La Rioja (UTC-3)'), ('America/Argentina/San_Juan', 'Argentina - San Juan (UTC-3)'), ('America/Argentina/Jujuy', 'Argentina - Jujuy (UTC-3)'), ('America/Argentina/Catamarca', 'Argentina - Catamarca (UTC-3)'), ('America/Argentina/Mendoza', 'Argentina - Mendoza (UTC-3)'), ('America/Argentina/San_Luis', 'Argentina - San Luis (UTC-3)'), ('America/Argentina/Rio_Gallegos', 'Argentina - Río Gallegos (UTC-3)'), ('America/Argentina/Ushuaia', 'Argentina - Ushuaia (UTC-3)'), ('America/Santiago', 'Chile - Santiago (UTC-4)'), ('Pacific/Easter', 'Chile - Easter Island (UTC-6)'), ('America/Asuncion', 'Paraguay - Asunción (UTC-4)'), ('America/Montevideo', 'Uruguay - Montevideo (UTC-3)')], default='America/Argentina/Buenos_Aires', max_length=50),
        ),
        migrations.CreateModel(
            name='ISPCubeIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.CharField(help_text="ISPCube subdomain (e.g., 'yourcompany' for yourcompany.ispcube.com)", max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(help_text='Stored encrypted', max_length=255)),
                ('api_key', models.CharField(help_text='Static API key provided by ISPCube', max_length=255)),
                ('api_token', models.TextField(blank=True, help_text='Dynamic token obtained from login', null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='Token expiration timestamp', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ispcube_integrations', to='api.company')),
            ],
            options={
                'verbose_name': 'ISPCube Integration',
                'verbose_name_plural': 'ISPCube Integrations',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'subdomain')},
            },
        ),
    ]
