# Generated by Django 5.2.7 on 2025-10-28 21:25

import api.fields.encrypted
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_company_timezone_ispcubeintegration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ispcubeintegration',
            name='api_key',
            field=api.fields.encrypted.EncryptedCharField(help_text='Static API key provided by ISPCube (encrypted)', max_length=500),
        ),
        migrations.AlterField(
            model_name='ispcubeintegration',
            name='api_token',
            field=api.fields.encrypted.EncryptedTextField(blank=True, help_text='Dynamic token obtained from login (encrypted)', null=True),
        ),
        migrations.AlterField(
            model_name='ispcubeintegration',
            name='password',
            field=api.fields.encrypted.EncryptedCharField(help_text='Stored encrypted with Fernet', max_length=500),
        ),
    ]
