# Generated by Django 5.2.7 on 2025-10-28 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_ispcubeintegration_api_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='External system identifier', max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional flexible data')),
                ('last_interaction', models.DateTimeField(blank=True, help_text='Last interaction timestamp', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='api.company')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-last_interaction', '-created_at'],
                'indexes': [models.Index(fields=['company', 'phone'], name='api_custome_company_f8631f_idx'), models.Index(fields=['company', 'email'], name='api_custome_company_fa0a1d_idx'), models.Index(fields=['last_interaction'], name='api_custome_last_in_b0447d_idx')],
                'unique_together': {('company', 'external_id')},
            },
        ),
    ]
