# Generated by Django 5.2.7 on 2025-10-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('bot_active', 'Bot Active'), ('awaiting_customer', 'Awaiting Customer'), ('escalated', 'Escalated'), ('transferred', 'Transferred to Agent'), ('agent_active', 'Agent Active'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('archived', 'Archived')], default='new', max_length=30),
        ),
    ]
