# Generated by Django 5.2.7 on 2025-10-28 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_conversation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='api.customer'),
        ),
    ]
