# Generated by Django 5.2.7 on 2025-10-28 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_conversation_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant (Bot)'), ('agent', 'Agent (Human)'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('tokens_used', models.PositiveIntegerField(default=0, help_text='Tokens consumed by this message')),
                ('latency_ms', models.PositiveIntegerField(blank=True, help_text='Response latency in milliseconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='api_message_convers_ece45b_idx'), models.Index(fields=['conversation', 'role'], name='api_message_convers_510ba6_idx')],
            },
        ),
    ]
