# Generated by Django 5.2.7 on 2025-10-28 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(help_text='Name of the tool/function called', max_length=255)),
                ('arguments', models.JSONField(help_text='Arguments passed to the tool')),
                ('response', models.JSONField(help_text='Response received from the tool')),
                ('duration_ms', models.PositiveIntegerField(help_text='Execution duration in milliseconds')),
                ('success', models.BooleanField(default=True, help_text='Whether the tool call succeeded')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='api.message')),
            ],
            options={
                'verbose_name': 'Tool Call Log',
                'verbose_name_plural': 'Tool Call Logs',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['message', 'created_at'], name='api_toolcal_message_b86bee_idx'), models.Index(fields=['tool_name', 'success'], name='api_toolcal_tool_na_c30271_idx')],
            },
        ),
    ]
