# Generated by Django 5.2.7 on 2025-10-29 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_toolcalllog'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Question or topic')),
                ('answer', models.TextField(help_text='Answer or information')),
                ('category', models.CharField(blank=True, help_text="Category for organization (e.g., 'billing', 'technical', 'general')", max_length=100)),
                ('keywords', models.JSONField(blank=True, default=list, help_text='Keywords for search and matching (array of strings)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this entry is active for bot use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base_entries', to='api.company')),
            ],
            options={
                'verbose_name': 'Knowledge Base Entry',
                'verbose_name_plural': 'Knowledge Base Entries',
                'ordering': ['category', '-created_at'],
                'indexes': [models.Index(fields=['company', 'is_active'], name='api_knowled_company_68c513_idx'), models.Index(fields=['company', 'category'], name='api_knowled_company_f742f7_idx')],
            },
        ),
    ]
