# Generated by Django 5.2.7 on 2025-10-29 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_knowledgebase'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentHandoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason for escalation to human agent')),
                ('assigned_agent', models.CharField(blank=True, help_text='Name or ID of assigned agent', max_length=255)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the agent resolved the issue', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or resolution details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_handoffs', to='api.conversation')),
            ],
            options={
                'verbose_name': 'Agent Handoff',
                'verbose_name_plural': 'Agent Handoffs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='api_agentha_convers_f282a3_idx'), models.Index(fields=['assigned_agent', 'resolved_at'], name='api_agentha_assigne_1c05b0_idx')],
            },
        ),
    ]
