# Generated by Django 5.2.7 on 2025-10-29 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_agenthandoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenthandoff',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_handoffs', to='api.conversation'),
        ),
    ]
