# Generated by Django 5.2.7 on 2025-10-29 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_agenthandoff_conversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name for identification', max_length=255)),
                ('content', models.TextField(help_text='Template content/message')),
                ('trigger_keywords', models.JSONField(blank=True, default=list, help_text='Keywords that trigger this template (array of strings)')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times this template has been used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='api.company')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'ordering': ['-usage_count', 'name'],
                'indexes': [models.Index(fields=['company', 'usage_count'], name='api_templat_company_84ac41_idx')],
                'unique_together': {('company', 'name')},
            },
        ),
    ]
