# Generated by Django 5.2.7 on 2025-10-29 17:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='feedback', serialize=False, to='api.conversation')),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 (poor) to 5 (excellent)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Customer feedback comments')),
                ('resolved_issue', models.BooleanField(default=False, help_text='Whether the issue was resolved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rating', 'resolved_issue'], name='api_feedbac_rating_4034cc_idx')],
            },
        ),
    ]
