# Generated by Django 5.2.7 on 2025-10-29 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_feedback'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='api_custome_company_f8631f_idx',
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('company', 'external_id'), ('company', 'phone')},
        ),
    ]
