# Generated by Django 5.2.7 on 2025-10-29 17:42

import api.fields.phone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_customer_api_custome_company_f8631f_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=api.fields.phone.E164PhoneNumberField(help_text='Phone number in E.164 format (e.g., +5491112345678)', max_length=20),
        ),
    ]
