# Generated by Django 5.2.7 on 2025-10-29 18:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('subscription', 'Subscription'), ('overage', 'Overage')], max_length=20)),
                ('description', models.TextField(help_text='Description of the billing event')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity of units', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount (quantity × unit_price)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('period_start', models.DateField(help_text='Billing period start date')),
                ('period_end', models.DateField(help_text='Billing period end date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_events', to='api.company')),
            ],
            options={
                'verbose_name': 'Billing Event',
                'verbose_name_plural': 'Billing Events',
                'ordering': ['-period_start', '-created_at'],
                'indexes': [models.Index(fields=['company', 'event_type'], name='api_billing_company_a6896a_idx'), models.Index(fields=['company', 'period_start', 'period_end'], name='api_billing_company_bbd27c_idx')],
            },
        ),
    ]
