# Generated by Django 5.2.7 on 2025-10-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_billingevent'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversation',
            name='api_convers_company_e691f6_idx',
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='api_convers_is_acti_4368ab_idx',
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['company', 'customer', 'is_active'], name='api_convers_company_70ba57_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['company', 'last_message_at'], name='api_convers_company_71995c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['customer', 'created_at'], name='api_convers_custome_887ac5_idx'),
        ),
    ]
