# Generated by Django 5.2.7 on 2025-10-29 20:21

import django.contrib.postgres.fields
from django.db import migrations, models


def convert_jsonb_to_array(apps, schema_editor):
    """Convert JSONB arrays to PostgreSQL array format."""
    # Add temporary columns
    schema_editor.execute(
        "ALTER TABLE api_knowledgebase ADD COLUMN keywords_array varchar(100)[] DEFAULT '{}'::varchar[]"
    )
    schema_editor.execute(
        "ALTER TABLE api_template ADD COLUMN trigger_keywords_array varchar(100)[] DEFAULT '{}'::varchar[]"
    )
    
    # Copy and convert data
    schema_editor.execute(
        """
        UPDATE api_knowledgebase 
        SET keywords_array = ARRAY(
            SELECT jsonb_array_elements_text(keywords)
        )
        WHERE keywords != '[]'::jsonb
        """
    )
    schema_editor.execute(
        """
        UPDATE api_template 
        SET trigger_keywords_array = ARRAY(
            SELECT jsonb_array_elements_text(trigger_keywords)
        )
        WHERE trigger_keywords != '[]'::jsonb
        """
    )
    
    # Drop old columns
    schema_editor.execute("ALTER TABLE api_knowledgebase DROP COLUMN keywords")
    schema_editor.execute("ALTER TABLE api_template DROP COLUMN trigger_keywords")
    
    # Rename new columns
    schema_editor.execute("ALTER TABLE api_knowledgebase RENAME COLUMN keywords_array TO keywords")
    schema_editor.execute("ALTER TABLE api_template RENAME COLUMN trigger_keywords_array TO trigger_keywords")


def convert_array_to_jsonb(apps, schema_editor):
    """Reverse migration: convert PostgreSQL array back to JSONB."""
    # Add temporary columns
    schema_editor.execute(
        "ALTER TABLE api_knowledgebase ADD COLUMN keywords_jsonb jsonb DEFAULT '[]'::jsonb"
    )
    schema_editor.execute(
        "ALTER TABLE api_template ADD COLUMN trigger_keywords_jsonb jsonb DEFAULT '[]'::jsonb"
    )
    
    # Copy and convert data
    schema_editor.execute(
        "UPDATE api_knowledgebase SET keywords_jsonb = to_jsonb(keywords)"
    )
    schema_editor.execute(
        "UPDATE api_template SET trigger_keywords_jsonb = to_jsonb(trigger_keywords)"
    )
    
    # Drop old columns
    schema_editor.execute("ALTER TABLE api_knowledgebase DROP COLUMN keywords")
    schema_editor.execute("ALTER TABLE api_template DROP COLUMN trigger_keywords")
    
    # Rename new columns
    schema_editor.execute("ALTER TABLE api_knowledgebase RENAME COLUMN keywords_jsonb TO keywords")
    schema_editor.execute("ALTER TABLE api_template RENAME COLUMN trigger_keywords_jsonb TO trigger_keywords")


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_conversation_api_convers_company_e691f6_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_jsonb_to_array, convert_array_to_jsonb),
        migrations.AlterField(
            model_name='knowledgebase',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Keywords for search and matching (array of strings)', size=None),
        ),
        migrations.AlterField(
            model_name='template',
            name='trigger_keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Keywords that trigger this template (array of strings)', size=None),
        ),
    ]

