# Generated by Django 5.2.7 on 2025-10-29 20:23

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_knowledgebase_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='external_id',
            field=models.CharField(blank=True, help_text='External system identifier', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='knowledgebase',
            index=django.contrib.postgres.indexes.GinIndex(fields=['keywords'], name='kb_keywords_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=django.contrib.postgres.indexes.GinIndex(fields=['trigger_keywords'], name='template_keywords_gin_idx'),
        ),
    ]
