# Generated by Django 5.2.7 on 2025-10-31 18:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_customer_external_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_prompt', models.TextField(default='Sos un asistente de soporte para {company_name}. Ayudás con consultas sobre servicio de Internet. Sé amable y profesional.', help_text='System prompt for the AI assistant. Use {company_name} as placeholder.')),
                ('max_tokens', models.PositiveIntegerField(default=500, help_text='Maximum tokens for AI response', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8192)])),
                ('temperature', models.FloatField(default=0.7, help_text='Creativity level (0.0-2.0). Lower is more focused, higher is more creative.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='api.company')),
            ],
            options={
                'verbose_name': 'Company Configuration',
                'verbose_name_plural': 'Company Configurations',
            },
        ),
    ]
