# Generated by Django 5.2.7 on 2025-11-05 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_companyconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('system_prompt', models.TextField(blank=True, help_text='General system prompt for this sector, applied to all companies in this sector')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='api_sector_name_f8e97c_idx')],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='sector',
            field=models.ForeignKey(blank=True, help_text='Industry sector for this company (e.g., ISP, Retail, Healthcare)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='api.sector'),
        ),
    ]
