# Generated by Django 5.2.7 on 2025-11-21 22:32

import api.fields.encrypted
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_sector_company_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ispcubeintegration',
            name='api_key',
            field=api.fields.encrypted.EncryptedCharField(help_text='Static API key provided by ISPCube staff (stored encrypted)', max_length=500),
        ),
        migrations.AlterField(
            model_name='ispcubeintegration',
            name='api_token',
            field=api.fields.encrypted.EncryptedTextField(blank=True, help_text='Dynamic bearer token obtained from authentication (stored encrypted, refreshed every 24h)', null=True),
        ),
        migrations.AlterField(
            model_name='ispcubeintegration',
            name='password',
            field=api.fields.encrypted.EncryptedCharField(help_text='API password provided by ISPCube staff (stored encrypted)', max_length=500),
        ),
        migrations.AlterField(
            model_name='ispcubeintegration',
            name='subdomain',
            field=models.CharField(help_text="ISPCube subdomain from your login URL (e.g., 'online24' for https://online24.ispcube.com). Provided by ISPCube staff.", max_length=255),
        ),
        migrations.AlterField(
            model_name='ispcubeintegration',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, help_text='Token expiration timestamp (ISPCube tokens are valid for 24 hours)', null=True),
        ),
        migrations.AlterField(
            model_name='ispcubeintegration',
            name='username',
            field=models.CharField(help_text='API username provided by ISPCube staff', max_length=255),
        ),
    ]
