app = "jarvisp-prod"
primary_region = "gru"

[build]
  dockerfile = "backend/Dockerfile"

[deploy]
  release_command = "uv run python manage.py migrate"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[env]
  DJANGO_SETTINGS_MODULE = "config.settings"
  PORT = "8000"
